version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile

    container_name: StuQrCodeGeneratorContainer
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html/qrgen/ && apache2-foreground"