version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: StuQrCodeGeneratorContainer
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html
